'use client'

import { useEffect, useState } from 'react'
import { Lightbulb, FileText, Code2, Briefcase, RefreshCw, ExternalLink, Sparkles } from 'lucide-react'
import type { TealCoaching } from '@/types'

interface CoachResult {
  ready: boolean
  jobsConsidered: number
  coaching: TealCoaching | null
}

const card: React.CSSProperties = { background: 'var(--card)', border: '1px solid var(--border2)', borderRadius: '10px', padding: '14px', marginBottom: '12px' }
const head: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: '7px', marginBottom: '13px' }
const headTitle: React.CSSProperties = { fontSize: '13px', fontWeight: 600, color: 'var(--text)' }
const chip: React.CSSProperties = { fontSize: '10px', background: 'var(--card2)', border: '1px solid var(--border)', color: 'var(--text3)', padding: '1px 6px', borderRadius: '4px' }
const prioStyle: Record<string, React.CSSProperties> = {
  high:   { background: '#200a0a', border: '1px solid #401010', color: '#b05050' },
  medium: { background: '#1e1a0a', border: '1px solid #3d3010', color: '#C9A96E' },
  low:    { background: '#0a1a0e', border: '1px solid #1a3520', color: '#5a9a6a' },
}

export default function TealCoach() {
  const [data, setData] = useState<CoachResult | null>(null)
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)

  async function load(refresh = false) {
    if (refresh) setRefreshing(true)
    try {
      const r = await fetch(`/api/teal/coach${refresh ? '?refresh=1' : ''}`).then(r => r.json())
      setData(r)
    } catch {
      setData({ ready: false, jobsConsidered: 0, coaching: null })
    } finally { setLoading(false); setRefreshing(false) }
  }
  useEffect(() => { load() }, [])

  if (loading) return <div style={{ ...card, fontSize: '12px', color: 'var(--text3)' }}>Teal is thinking…</div>

  // Gate: needs 3 scraped jobs before there's anything to optimise against.
  if (!data?.ready || !data.coaching) {
    return (
      <div style={{ ...card, textAlign: 'center', padding: '28px 16px' }}>
        <Sparkles size={22} style={{ color: 'var(--text3)', marginBottom: '8px' }} />
        <div className="font-head" style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text)', marginBottom: '4px' }}>Teal is waiting for jobs to scrape</div>
        <div style={{ fontSize: '12px', color: 'var(--text3)', lineHeight: 1.5, maxWidth: '380px', margin: '0 auto' }}>
          Once 3 jobs land in your tracker ({data?.jobsConsidered ?? 0}/3 so far), Teal will map the skills they share, how to retune your CV, and what to drill.
        </div>
      </div>
    )
  }

  const c = data.coaching

  return (
    <>
      {/* Summary + refresh */}
      <div style={card}>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '10px' }}>
          <div style={{ fontSize: '12.5px', color: 'var(--text2)', lineHeight: 1.6 }}>{c.summary}</div>
          <button onClick={() => load(true)} disabled={refreshing} title="Regenerate"
            style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '10px', padding: '5px 9px', borderRadius: '6px', border: '1px solid var(--border)', background: 'var(--card2)', color: 'var(--text3)', cursor: 'pointer', fontFamily: 'inherit', whiteSpace: 'nowrap' }}>
            <RefreshCw size={11} className={refreshing ? 'spin' : ''} /> {refreshing ? 'Working' : 'Refresh'}
          </button>
        </div>
        <div style={{ marginTop: '8px', fontSize: '10px', color: 'var(--text3)' }}>
          {c.source === 'claude' ? 'Generated by Claude' : 'Heuristic plan — add ANTHROPIC_API_KEY for AI coaching'} · based on {c.jobsConsidered} scraped jobs
        </div>
      </div>

      {/* Skills to acquire (common across the jobs) */}
      <div style={card}>
        <div style={head}>
          <Lightbulb size={14} style={{ color: 'var(--amber)' }} />
          <span className="font-head" style={headTitle}>Skills to acquire for these roles</span>
        </div>
        {c.skillsToAcquire.map((s, i) => (
          <div key={`${s.skill}-${i}`} style={{ padding: '9px 0', borderBottom: i < c.skillsToAcquire.length - 1 ? '1px solid var(--border2)' : 'none' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '3px' }}>
              <span style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text)' }}>{s.skill}</span>
              <span style={{ fontSize: '10px', padding: '1px 6px', borderRadius: '4px', ...prioStyle[s.priority] }}>{s.priority}</span>
              {s.appearsInJobs > 0 && <span style={chip}>in {s.appearsInJobs}/{c.jobsConsidered} jobs</span>}
            </div>
            <div style={{ fontSize: '11.5px', color: 'var(--text3)', lineHeight: 1.5 }}>{s.rationale}</div>
          </div>
        ))}
      </div>

      {/* Resume suggestions */}
      <div style={card}>
        <div style={head}>
          <FileText size={14} style={{ color: 'var(--amber)' }} />
          <span className="font-head" style={headTitle}>How to tune your resume</span>
        </div>
        {c.resumeSuggestions.map((r, i) => (
          <div key={i} style={{ display: 'flex', gap: '10px', padding: '8px 0', borderBottom: i < c.resumeSuggestions.length - 1 ? '1px solid var(--border2)' : 'none' }}>
            <span style={{ ...chip, flexShrink: 0, alignSelf: 'flex-start', marginTop: '1px' }}>{r.section}</span>
            <span style={{ fontSize: '12px', color: 'var(--text2)', lineHeight: 1.5 }}>{r.change}</span>
          </div>
        ))}
      </div>

      {/* Practice CTA */}
      <div style={card}>
        <div style={head}>
          <Code2 size={14} style={{ color: 'var(--amber)' }} />
          <span className="font-head" style={headTitle}>Sharpen your interview prep</span>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
          {c.practice.map((p, i) => (
            <a key={i} href={p.url} target="_blank" rel="noopener noreferrer"
              style={{ flex: '1 1 220px', textDecoration: 'none', display: 'block', background: 'var(--card2)', border: '1px solid var(--border)', borderRadius: '8px', padding: '11px 12px' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px' }}>
                <span style={{ fontSize: '12.5px', fontWeight: 600, color: 'var(--amber)' }}>{p.platform}</span>
                <ExternalLink size={12} style={{ color: 'var(--text3)' }} />
              </div>
              <div style={{ fontSize: '11px', color: 'var(--text2)', lineHeight: 1.4 }}>Focus: {p.focus}</div>
            </a>
          ))}
        </div>
      </div>

      {/* Freelance work */}
      <div style={card}>
        <div style={head}>
          <Briefcase size={14} style={{ color: 'var(--amber)' }} />
          <span className="font-head" style={headTitle}>Freelance work to build experience</span>
        </div>
        {c.freelance.map((f, i) => (
          <a key={i} href={f.url} target="_blank" rel="noopener noreferrer"
            style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 0', borderBottom: i < c.freelance.length - 1 ? '1px solid var(--border2)' : 'none' }}>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: '12.5px', color: 'var(--text)', fontWeight: 500 }}>{f.title}</div>
              <div style={{ display: 'flex', gap: '5px', marginTop: '4px', flexWrap: 'wrap' }}>
                <span style={chip}>{f.skill}</span>
                {f.rate && <span style={{ ...chip, color: '#5a9a6a', background: '#0a1a0e', borderColor: '#1a3520' }}>{f.rate}</span>}
              </div>
            </div>
            <span style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '11px', color: 'var(--amber)', whiteSpace: 'nowrap' }}>
              {f.platform} <ExternalLink size={12} />
            </span>
          </a>
        ))}
      </div>
    </>
  )
}
